name: test
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Fetching changes
        uses: actions/checkout@v4
      
      - name: Fetching Python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.12'
      
      - name: Installing dependecies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Running tests
        run: pytest
